### ISSUE TITLE
Simulator build failing on Xcode 11.6

### ISSUE THREAD

**Issue by adib** [keeshux/openssl-apple#19]
The scripts doesn't seem be working with Xcode 11.6. Building for the iOS Simulator failed due to what seems to be a linker flag problem.

Example invocation:

```bash
 caffeinate ./build-libssl.sh   --version=1.1.1g --archs="ios_x86_64"
```

Error:

```
ld: building for iOS Simulator, but linking in .tbd file (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd) built for macOS/Mac Catalyst, file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64
```

Full log here: [build-openssl-1.1.1g.log.gz](https://github.com/keeshux/openssl-apple/files/5044668/build-openssl-1.1.1g.log.gz)

**Comment by keeshux** [comment]
Output of `/build-libssl.sh --help`:

> Options for OpenSSL 1.0.2 and lower ONLY
>     --archs="ARCH ARCH ..." 

Use `--targets` instead.
