### ISSUE TITLE
Question about iOS target bump

### ISSUE THREAD

**Issue by pahnev** [keeshux/openssl-apple#27]
Hi, thank you for figuring out the Xcode 12 and Apple silicon support.
I was just wondering what was the reason behind bumping the iOS target to 12.0 in https://github.com/keeshux/openssl-apple/commit/340537f48eff15050a0ad581815cf9808f603f97? Does the XCFramework not support iOS 11 or was there something else in the build process?

**Comment by keeshux** [comment]
It came when upgrading project to Xcode 12.2 apparently.

**Comment by pahnev** [comment]
I've also seen that Xcode 12 "Update to recommended settings" bumps the version to 12.0, even though there's no reason for it.
Would it be possible to lower this and TunnelKit back to 11.0?

**Comment by keeshux** [comment]
I’d rather push legacy away when Apple means it -and man they did mean it with that move. Retaining it is asking for trouble, so no. Sorry.

**Comment by keeshux** [comment]
I’d have discussed macOS target which is more of a fuzzy area, as I can’t find decent documentation to choose a proper target wisely. It’s rough trial and error for me based on compiler errors/warnings or at times just to simplify and move on.
