### ISSUE TITLE
Wrong minimum iOS version in Info.plist for iPhoneOS

### ISSUE THREAD

**Issue by sanyesz123** [keeshux/openssl-apple#30]
Branch: master

Steps to reproduce:
- used targets ios-sim-cross-x86_64 ios-sim-cross-arm64 ios64-cross-arm64 (ios-sim-cross-arm64 is added)
- min-ios-sdk is set to 12.0

Result: 
In the generated iPhoneOS framework the Info.plist contains 13.0 as minimum iOS version, but in the iPhoneSimulator framework's Info.plist contains 12.0.

Expected:
Both folders should contain min iOS version 12.0 in the Info.plist.

**Comment by keeshux** [comment]
@sanyesz123 let me know if the fix is correct, as I was facing a similar issue in my iOS app (warnings about linking 13.0 library against 12.0 app).

**Comment by sanyesz123** [comment]
@keeshux please for the quick fix, I will check it. Based on your changes, this means the arm64 simulators will support only iOS apps with minimum iOS 13.0?

**Comment by keeshux** [comment]
It seems to be the case, the argument name (`-target arm64-apple-ios13.0-simulator`) pretty much sums it up.
