### ISSUE TITLE
Missing symbolic links for Catalyst target

### ISSUE THREAD

**Issue by ilkerc** [keeshux/openssl-apple#32]
Catalyst build framework is missing symbolic links whereas the macOS build framework has. App Store processing defines these are malformed frameworks thus invalid build. Should we add Catalyst for symbolic link creation too, or am I missing something?

https://github.com/keeshux/openssl-apple/blob/7eb1ce9894c4f7f2d19895e1a044d3583d20f089/create-openssl-framework.sh#L244

![Image 2020-12-09 at 7 13 31 PM](https://user-images.githubusercontent.com/6921843/101655454-b0a0f580-3a52-11eb-8cd0-03fe50b90236.jpg)

```
 ITMS-90291: Malformed Framework - The framework bundle openssl (x.app/Contents/Frameworks/openssl.framework) must contain a symbolic link 'openssl' -> 'Versions/Current/openssl'. Refer to the Anatomy of Framework Bundles for more information.

ITMS-90291: Malformed Framework - The framework bundle openssl (x.app/Contents/Frameworks/openssl.framework) must contain a symbolic link 'Resources' -> 'Versions/Current/Resources'. Refer to the Anatomy of Framework Bundles for more information.

ITMS-90292: Malformed Framework - The framework bundle openssl (x.app/Contents/Frameworks/openssl.framework) 'Versions' directory must contain a symbolic link 'Current' resolving to a specific version directory. Resolved link target: '${linkTarget}'. Refer to the Anatomy of Framework Bundles for more information.
```

**Comment by keeshux** [comment]
I've never released a Catalyst app but I assume this is something to fix.

**Comment by ilkerc** [comment]
@keeshux I submit a new version to the App Store with symbolic links, I didn't get any `Malformed Framework` error after processing. I will create a PR regarding this.
