### ISSUE TITLE
"Problem during configure ..."

### ISSUE THREAD

**Issue by KhizhniakovM** [keeshux/openssl-apple#37]
Can't build openssl for any archs by using build-libssl.sh 

Has that problem 
<img width="630" alt="Screenshot 2021-02-03 at 12 24 29" src="https://user-images.githubusercontent.com/63532391/106726607-a139c500-661b-11eb-92b0-5ddb19f08624.png">

Don't understand what is the problem and how to solve it.
Please help with it!

**Comment by keeshux** [comment]
There is no problem in your output. So...

**Comment by KhizhniakovM** [comment]
Sorry, problem is the same as https://github.com/keeshux/openssl-apple/issues/12

**Comment by keeshux** [comment]
Either you provide full and relevant info, or I'm gonna to have to close the issue.

**Comment by KhizhniakovM** [comment]
Sorry, my inattention is the root of all evil. There was no problem with your code.
