### ISSUE TITLE
Cannot Build - symbol(s) not found for architecture i386

### ISSUE THREAD

**Issue by VinylCarbon** [keeshux/openssl-apple#6]
Hi, when trying to use this as a cocoapods dependancy, I get the following messages:

[!] /bin/bash -c 
set -e
./build-libssl.sh --version=1.1.0h
./create-openssl-framework.sh dynamic

Build options
  OpenSSL version: 1.1.0h
  Targets: ios-sim-cross-x86_64 ios-sim-cross-i386 ios64-cross-arm64 ios-cross-armv7s ios-cross-armv7 tvos-sim-cross-x86_64 tvos64-cross-arm64 macos64-x86_64 macos-i386
  macOS SDK: 10.14
  iOS SDK: 12.1
  tvOS SDK: 12.1
  Number of make threads: 8
  Configure options:  no-deprecated
  Build location: /Users/mikebowyer/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.0h-cd153

Downloading openssl-1.1.0h.tar.gz...
Building openssl-1.1.0h for iPhoneSimulator 12.1 x86_64...
  Logfile: /Users/mikebowyer/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.0h-cd153/bin/iPhoneSimulator12.1-x86_64.sdk/build-openssl-1.1.0h.log
  Configure...
  Make (using 8 thread(s))...
Building openssl-1.1.0h for iPhoneSimulator 12.1 i386...
  Logfile: /Users/mikebowyer/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.0h-cd153/bin/iPhoneSimulator12.1-i386.sdk/build-openssl-1.1.0h.log
  Configure...
  Make (using 8 thread(s))...
Building openssl-1.1.0h for iPhoneOS 12.1 arm64...
  Logfile: /Users/mikebowyer/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.0h-cd153/bin/iPhoneOS12.1-arm64.sdk/build-openssl-1.1.0h.log
  Configure...
  Make (using 8 thread(s))...
Building openssl-1.1.0h for iPhoneOS 12.1 armv7s...
  Logfile: /Users/mikebowyer/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.0h-cd153/bin/iPhoneOS12.1-armv7s.sdk/build-openssl-1.1.0h.log
  Configure...
  Make (using 8 thread(s))...
Building openssl-1.1.0h for iPhoneOS 12.1 armv7...
  Logfile: /Users/mikebowyer/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.0h-cd153/bin/iPhoneOS12.1-armv7.sdk/build-openssl-1.1.0h.log
  Configure...
  Make (using 8 thread(s))...
Building openssl-1.1.0h for AppleTVSimulator 12.1 x86_64...
  Logfile: /Users/mikebowyer/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.0h-cd153/bin/AppleTVSimulator12.1-x86_64.sdk/build-openssl-1.1.0h.log
  Configure...
  Make (using 8 thread(s))...
Building openssl-1.1.0h for AppleTVOS 12.1 arm64...
  Logfile: /Users/mikebowyer/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.0h-cd153/bin/AppleTVOS12.1-arm64.sdk/build-openssl-1.1.0h.log
  Configure...
  Make (using 8 thread(s))...
Building openssl-1.1.0h for MacOSX 10.14 x86_64...
  Logfile: /Users/mikebowyer/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.0h-cd153/bin/MacOSX10.14-x86_64.sdk/build-openssl-1.1.0h.log
  Configure...
  Make (using 8 thread(s))...
Building openssl-1.1.0h for MacOSX 10.14 i386...
  Logfile: /Users/mikebowyer/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.0h-cd153/bin/MacOSX10.14-i386.sdk/build-openssl-1.1.0h.log
  Configure...
  Make (using 8 thread(s))...
Problem during make - Please check /Users/mikebowyer/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.0h-cd153/bin/MacOSX10.14-i386.sdk/build-openssl-1.1.0h.log

Then the output from the log is here:
[build-openssl-1.1.0h.log](https://github.com/keeshux/openssl-apple/files/2923046/build-openssl-1.1.0h.log)

Have done a bit of research but cannot find anything similar, probably something simple that I am missing, but any help would be great. Thanks :)

**Comment by keeshux** [comment]
Hi! I recently made tweaks to only build the library on 64-bit archs. If you set your `Podfile` to use `1.1.0i` (instead of `h`), you should be good to go. Nevertheless, if you're linking to a 32-bit project, this will not work any longer.

**Comment by VinylCarbon** [comment]
@keeshux Thank you, I will give it a go and report back.
